apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myjavaapp-deploy
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.7.1
    spec:
      containers:
      - name: myjavaapp-pod
        image: maha4iac/mymahalogin:1
        ports:
        - containerPort:  8080
          protocol: TCP