apiVersion: v1
kind: Service
metadata:
  name: mytomcat-svc
  labels:
    app: mytomcat
    version: 2.7.1
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    protocol: TCP
  selector:
    app: mytomcat
    version: 2.7.1